name: Python Code Quality Check

on:
  push:
    branches:
      - main
  
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint with flake8
        run: |
         flake8 src/ --count --show-source --statistics --builtins=spark,dbutils,display --max-line-length=120 --ignore=W291,W292,W293,F541,E261,E501
